version: "3.8"

services:
  user-service:
    build: ./user-service
    container_name: user-service
    ports:
      - "3001:3001"
    depends_on:
      - mongo-user

  product-service:
    build: ./product-service
    ports:
      - "3002:3002"
    depends_on:
      - mongo-product

  order-service:
    build: ./order-service
    ports:
      - "3003:3003"
    depends_on:
      - mongo-order

  mongo-user:
    image: mongo
    container_name: mongo-user
    ports:
      - "27017:27017"

  mongo-product:
    image: mongo
    ports:
      - "27018:27017"

  mongo-order:
    image: mongo
    ports:
      - "27019:27017"
